member/urls.py
from django.conf.urls import url
from . import views

app_name = 'member'
urlpatterns=[
    url(r'^list/$', views.member_list, name='member_list'),
    url(r'^list/(?P<member_id>[0-9]*)/$',views.member_detail, name='member_detail'),
    url(r'^add/',views.member_add_xx, name='member_add'),
    url(r'^delet/(?P<member_id>[0-9]*)/$',views.member_delet, name='member_delet'),
    # url(r'^list/type/(?P<member_with_type_id>[0-9]*)/$',views.member_with_type,name='member_with_type'),
    #url(r'^date/(?P<year>[0-9]*)/(?P<month>[0-9]*)/(?P<day>[0-9]*)/$',views.blog_with_date,name='blog_with_date'),
]

member_manage/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from member import views
# from xsxx import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home',views.home,name='home'),
    url(r'^member/',include('member.urls')),
    url(r'^member_list',views.member_list,name='member_list'),
    # url(r'^xsxx/', include('xsxx.urls'), name='xsxx'),
]

member/models.py
from django.db import models


class Grqx(models.Model):
    QX = models.IntegerField()

    def __str__(self):
        return str(self.QX)


class Jbxx(models.Model):
    #低级 姓名，性别，年龄，院系，专业，年级，籍贯，所在部门，所在组，
    xh = models.CharField(max_length=20, verbose_name='学号')
    name = models.CharField(max_length=20,blank=True, null=True, verbose_name='姓名')
    sex = models.CharField(max_length=20,blank=True, null=True)
    age = models.IntegerField(blank=True, null=True, verbose_name='年龄')
    yx = models.CharField(max_length=20,blank=True, null=True,verbose_name='院系')
    zy = models.CharField(max_length=20,blank=True, null=True,verbose_name='专业')
    nj = models.CharField(max_length=20,blank=True, null=True,verbose_name='年级')
    jg = models.CharField(max_length=20,blank=True, null=True,verbose_name='籍贯')
    bm = models.CharField(max_length=20,blank=True, null=True,verbose_name='部门')
    zb = models.CharField(max_length=20,blank=True, null=True,verbose_name='组')
    #中级 QQ，邮箱，课表，项目经验，特长，
    qq = models.CharField(max_length=20,blank=True, null=True)
    email = models.CharField(max_length=20,blank=True, null=True)
    # kb =
    jy = models.TextField(blank=True, null=True,verbose_name='经验')
    tc = models.TextField(blank=True, null=True,verbose_name='特长')
    #高级 联系电话，加入团队间，有无考研意向，是否是勤工，银行卡号
    tel = models.CharField(max_length=20,blank=True, null=True)
    join_time =  models.DateTimeField(verbose_name='加入时间')
    SFKY = models.CharField(max_length=20,blank=True, null=True,verbose_name='是否考研')
    SFQG = models.CharField(max_length=20,blank=True, null=True,verbose_name='是否勤工')
    YHKH = models.CharField(max_length=20,blank=True, null=True,verbose_name='银行卡号')
    #权限
    QX = models.ForeignKey(Grqx,on_delete=models.DO_NOTHING,verbose_name='权限',default=1)
    # DLMM

    def __str__(self):
        return "<member : %s>" % self.xh


class Info(models.Model):
    xh = models.IntegerField(primary_key=True)
    info = models.TextField(blank=True, null=True)


class login(models.Model):
    user = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

member/views.py
from django.shortcuts import render,render_to_response,get_object_or_404
from .models import Grqx,Jbxx,Info
# from django.apps import apps
# import member

# Create your views here.
def home(request):
    context={}
    return render_to_response('home.html',context)

def member_list(request):
    context = {}
    context['members'] = Jbxx.objects.all()
    return render_to_response('member/member_list.html',context)

def member_detail(request,member_id):
    context = {}
    # modelobj = apps.get_model(member,Jbxx)
    # for field in modelobj._meta.fields:
    #     context[field.name] = field.verbose_name

    context['member'] = get_object_or_404(Jbxx,id=member_id)
    return render_to_response('member/member_detail.html',context)

# def member_add_xx(request):
#     if request.method == 'GET':
#         return render(request, 'addstu.html')
#
#     if request.method == 'POST':
#         stu_name = request.POST.get('name')
#         stu_num = request.POST.get('num')
#
#     context = {}
#     return render_to_response('member/member_add.html',context)

def member_add_xx(request):
    if request.method == 'GET':
        return render(request, 'member/member_add.html')

    if request.method == 'POST':
        xh = request.POST.get('xh')
        name = request.POST.get('name')
        sex = request.POST.get('sex')
        age = request.POST.get('age')
        yx = request.POST.get('yx')
        zy = request.POST.get('zy')
        nj = request.POST.get('nj')
        jg = request.POST.get('jg')
        bm = request.POST.get('bm')
        zb = request.POST.get('zb')
        qq = request.POST.get('qq')
        email = request.POST.get('email')
        jy = request.POST.get('jy')
        tc = request.POST.get('tc')
        tel = request.POST.get('tel')
        join_time = request.POST.get('join_time')
        SFKY = request.POST.get('SFKY')
        SFQG = request.POST.get('SFQG,')
        YHKH = request.POST.get('YHKH,')
        QX = request.POST.get('QX')

        if not Jbxx.objects.filter(xh=xh).exists():
            # jbxx = Jbxx()
            Jbxx.objects.create(
                xh=xh,
                name=name,
                sex =sex,
                age = age,
                yx = yx,
                zy = zy,
                nj = nj,
                jg = jg,
                bm = bm,
                zb = zb,
                qq = qq,
                email = email,
                jy = jy,
                tc = tc,
                tel = tel,
                join_time = join_time,
                SFKY = SFKY,
                SFQG = SFQG,
                YHKH = YHKH,
                QX = get_object_or_404(Grqx,QX=QX)
            ).save()
            return render(request, 'member/member_add.html',{'message': '提交成功'})
        else:
            return render(request, 'member/member_add.html', {'message': '该学号已经存在！'})

def member_delet(request,id):
    pass
    Jbxx.objects.get(id=id).delete()
    return HttpResponseRedirect('/stu/allstu')

def login():
    pass

def judge_qx():
    qx = Grqx.objects.filter()

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/base.css">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <script type="text/javascript" href="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" href="{% static 'jquery-1.12.4.min.js' %}"></script>
    {% block header_extends %}{% endblock %}
</head>
<body>
    {#导航栏#}
    <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home' %}">双零团队成员管理</a>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse" >
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar-collapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">首页</a></li>
                    <li><a href="{% url 'member:member_list' %}">成员</a></li>
                </ul>
            </div>
        </div>
    </div>
    {% block content %}{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    成员管理|首页
{% endblock %}

{% block header_extends %}
        <link rel="stylesheet" href="{% static 'home.css' %}">
{% endblock %}


{% block content %}
    <h1>双零团队</h1>
{#    <h3 class="home_content">欢迎访问我的网站</h3>#}
    <a href="{% url 'member:member_list' %}"><h2>成员列表</h2></a>
{% endblock %}

templates/member/member_add.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>#}
{#        {% block title %}#}
{#        {% endblock %}#}
{#    </title>#}
{#    <style>#}
{#        body {#}
{#            width: 960px;#}
{#            margin: 0 auto;#}
{#        }#}
{##}
{#        .center {#}
{#            text-align: center;#}
{#        }#}
{##}
{#        #menu {#}
{#            margin-bottom: 100px;#}
{#            margin-left: 276px;#}
{#        }#}
{##}
{#        #menu ul {#}
{##}
{#        }#}
{##}
{#        #menu li {#}
{#            float: left;#}
{#            list-style: none;#}
{#            margin-right: 20px;#}
{#        }#}
{##}
{#        #menu a {#}
{#            text-decoration: none;#}
{#        }#}
{##}
{#        #main {#}
{#            clear: both;#}
{#        }#}
{##}
{#        #footer {#}
{#            margin-top: 20px;#}
{#        }#}
{##}
{#        #main input {#}
{#            margin-bottom: 20px;#}
{#        }#}
{#    </style>#}
{#</head>#}
{#<body>#}
{#    <h1 class="center">#}
{#        {% block systemName %}#}
{#        {% endblock %}#}
{#    </h1>#}
{#    <div class="center"  id="menu">#}
{#        <ul>#}
{#            <li><a href="#">学生信息管理</a></li>#}
{#            <li><a href="#">课程信息管理</a></li>#}
{#            <li><a href="#">成绩信息管理</a></li>#}
{#        </ul>#}
{#    </div>#}
{#    <div id="main" class="center">#}
{#        {% block main %}#}
{#        {% endblock %}#}
{#    </div>#}
{##}
{#    <h2 id="footer" class="center">©Qingle 2018年</h2>#}
{#    <script src="/static/jquery-1.12.4.min.js"></script>#}
{#    <script>#}
{#        $(function () {#}
{#            if($('#message').val() != ""){#}
{#                alert($('#message').val());#}
{#                return#}
{#            }#}
{#        })#}
{#    </script>#}
{#</body>#}
{#</html>#}


{% extends "base.html" %}
{% block title %}
    添加学生信息
{% endblock %}


{% block content %}
    <h3 class="center">学生信息添加</h3>
    <input type="hidden" id="message" value="{{ message }}">
    <form action="{% url 'member:member_add' %}" method="post">
    {% csrf_token %}
        学号：<input type="text" name="xh"><br>
        姓名：<input type="text" name="name"><br>
        性别：<input type="text" name="sex"><br>
        年龄：<input type="text" name="age"><br>
        院系：<input type="text" name="yx"><br>
        专业：<input type="text" name="zy"><br>
        年级：<input type="text" name="nj"><br>
        籍贯：<input type="text" name="jg"><br>
        所在部门：<input type="text" name="bm"><br>
        所在组：<input type="text" name="zb"><br>
        QQ：<input type="text" name="qq"><br>
        邮箱：<input type="text" name="email"><br>
        项目经验：<input type="text" name="jy"><br>
        特长：<input type="text" name="tc"><br>
        联系电话：<input type="text" name="tel"><br>
        加入团队间：<input type="text" name="join_time"><br>
        有无考研意向：<input type="text" name="SFKY"><br>
        是否是勤工：<input type="text" name="SFQG"><br>
        银行卡号：<input type="text" name="YHKH"><br>
        权限：<input type="" name="QX"><br>
        <input type="submit" value="添加">
    </form>
{#    <script>#}
{#        $(function () {#}
{#            if($('#message').val() != ""){#}
{#                alert($('#message').val());#}
{#                return#}
{#            }#}
{#        })#}
{#    </script>#}
{% endblock %}

templates/member/member_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    成员管理|个人信息
{% endblock %}

{% block header_extends %}
        <link rel="stylesheet" href="{% static 'detail.css' %}">
{% endblock %}

{% block content %}
{#    {% for %}#}
{#    {{ field }}#}

    <ul>
        <li>学号：<a>{{ member.xh }} </a></li>
        <li>姓名：<a>{{member.name}}</a></li>
        <li>年龄：<a>{{member.age}}</a></li>
        <li>性别：<a>{{member.sex}}</a></li>
        <li>院系：<a>{{member.yx}}</a></li>
        <li>专业：<a>{{member.zy}}</a></li>
        <li>年级：<a>{{member.nj}}</a></li>
        <li>籍贯:<a>{{member.jg}}</a></li>
        <li>部门:<a>{{member.bm}}</a></li>
        <li>组别:<a>{{member.zb}}</a></li>
        <li>QQ：<a>{{member.qq}}</a></li>
        <li>邮箱：<a>{{member.email}}</a></li>
        <li>经验：<a>{{member.jy}}</a></li>
        <li>特长：<a>{{member.tc}}</a></li>
        <li>联系电话：<a>{{member.tel}}</a></li>
        <li>加入团队时间：<a>{{member.join_time}}</a></li>
        <li>是否考研：<a>{{member.SFKY}}</a></li>
        <li>是否勤工：<a>{{member.SFQG}}</a></li>
        <li>银行卡号：<a>{{member.YHKH}}</a></li>
        <li>权限等级：<a>{{member.QX}}</a></li>
    </ul>

{% endblock %}

templates/member/member_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    成员管理|成员列表
{% endblock %}

{% block header_extends %}
        <link rel="stylesheet" href="{% static 'list.css' %}">
{% endblock %}


{% block content %}
    <div>
        <a href="{% url 'member:member_add' %}">
            <h3>添加成员</h3>
        </a>
    </div>
    <div>
        {% for member in members  %}
            <a href="{% url 'member:member_detail' member.pk%}">
                <p>{{ member.xh }}</p>
            </a>
        {% endfor %}
    </div>

{% endblock %}